### ISSUE TITLE
Several APIs: Some properties are missing a type

### ISSUE THREAD

**Issue by alexklibisz** [googlemaps/openapi-specification#361]
Sorry for deleting your nice template. If there isn't an obvious solution to this, I'll come back and fill out the full template. For now the file is just too big to parse out the exact details you require, and the issue is relatively simple and widespread.

Some properties are missing a `type`. 

For example:

on line 23140:

```yaml
steps:
          description: Contains detailed directions for walking or driving steps in transit directions. Substeps are only available when travel_mode is set to "transit". The inner steps array is of the same type as steps.
```

And, on line 23288:

```yaml
partial_match:
          description: |
            Indicates that the geocoder did not return an exact match for the original request, though it was able to match part of the requested address. You may wish to examine the original request for misspellings and/or an incomplete address.

            Partial matches most often occur for street addresses that do not exist within the locality you pass in the request. Partial matches may also be returned when a request matches two or more locations in the same locality. For example, "21 Henr St, Bristol, UK" will return a partial match for both Henry Street and Henrietta Street. Note that if a request includes a misspelled address component, the geocoding service may suggest an alternative address. Suggestions triggered in this way will also be marked as a partial match.
```

This understandably trips up some code generators.

Is this expected behavior?
